### ISSUE TITLE
Limit exceeded

### ISSUE THREAD

**Issue by hari6696** [axibase/atsd-integration#5]
Tags request error: Invalid XML ; cvc-complex-type.2.4.f: 'ResourceId' can occur a maximum of '10' times in the current sequence. This limit was exceeded. No child element is expected at this point. (Service: AmazonRoute53; Status Code: 400; Error Code: InvalidInput; Request ID: 6fe6f7c6-c2f1-4ca2-8235-5b596d3d1345)
19:40:34.433 [main] WARN com.axibase.tsd.client.HttpClient - Server error: null
Exception in thread "main" com.axibase.tsd.client.AtsdServerException: No Content (204)
        at com.axibase.tsd.client.HttpClient.buildException(HttpClient.java:257)
        at com.axibase.tsd.client.HttpClient.getUpdateResult(HttpClient.java:248)
        at com.axibase.tsd.client.HttpClient.update(HttpClient.java:233)
        at com.axibase.tsd.client.HttpClient.updateMetaData(HttpClient.java:167)
        at com.axibase.tsd.client.HttpClientManager.updateMetaData(HttpClientManager.java:96)
        at com.axibase.tsd.client.MetaDataService.createOrReplaceEntity(MetaDataService.java:309)
        at Main.sendEntity(Main.java:178)
        at Main.main(Main.java:64)

**Comment by raipc** [comment]
@hari6696 Thank you for submission. The fix will be available soon.

**Comment by raipc** [comment]
@hari6696 Does the problem persist in latest revision?
